apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-cpu
  name: test-cpu
spec:
  containers:
  - image: nginx
    name: test-cpu
    resources: {}
  dnsPolicy: ClusterFirst
  nodeSelector:
    type: cpu
  restartPolicy: Always
status: {}