apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: test
    tier: backend
  name: test-pod
  namespace: custom-ns
spec:
  containers:
  - image: nginx:1.17
    name: test-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}