apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: q4
  name: q4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: q4
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        resources: {}
status: {}