apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q10
  name: q10
spec:
  nodeName: node01
  containers:
  - image: busybox
    name: q10
    command:
    - "sh"
    - "-c"
    - "sleep 1200"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}